#!/usr/bin/env python3
"""Regenerates jpx-corpus-references.txt: compares this decoder's output for every JPXDecode image of the fetched corpora with
OpenJPEG's (opj_decompress, 2.5.4 when written), standard library only.

1. Dump the decoder's output: BROADSIDE_CORPUS_DIR=<corpus> BROADSIDE_JPX_DUMP=<dir> dotnet test tests/Broadside.Tests
   --filter-class Broadside.Tests.Images.RealWorldJpxTests (the sweep fails while the table is stale; the dump is written anyway).
2. python3 jpx-corpus-references.py <dir> > jpx-corpus-references.txt

Each image's channels are compared with OpenJPEG's components after its JP2 processing (palette, component mapping, channel
definitions, sYCC to RGB): channel i with component i, the alpha plane with the component after the colours. With an Indexed
ColorSpace the decoder hands out the palette indices raw; they are mapped through the file's pclr box before the comparison.
Accepted: peak absolute error <= 4 and mean squared error <= 1 per channel (ITU-T T.803 tolerances used by OpenJPEG's own
conformance tests); 5/3-only images must be exact. A line records the measured errors; anything else is reported on stderr and
the script exits 1.
"""
import glob
import hashlib
import os
import struct
import subprocess
import sys
import tempfile

EXCLUSIONS = {
    ("pdfjs/issue19517.pdf", 8): "12608 x 16806 x 4 in one tile: more samples than the default MaxImagePixels (2^28); JpxLimitExceeded",
}


def pgx(path):
    raw = open(path, "rb").read()
    nl = raw.index(b"\n")
    head = raw[:nl].split()
    w, h = int(head[-2]), int(head[-1])
    sign = head[2] if len(head) == 6 else head[2][:1]
    depth = int(head[-3].lstrip(b"+-"))
    signed = b"-" in sign
    body = raw[nl + 1:]
    nbytes = 1 if depth <= 8 else 2
    big = head[1] == b"ML"
    vals = []
    for i in range(0, w * h * nbytes, nbytes):
        v = body[i] if nbytes == 1 else (body[i] << 8 | body[i + 1]) if big else (body[i + 1] << 8 | body[i])
        if signed and v >= 1 << (depth - 1):
            v -= 1 << depth
        vals.append(v)
    if signed:
        vals = [v + (1 << (depth - 1)) for v in vals]
    return w, h, depth, vals


def unpack(data, count, bits):
    if bits == 8:
        return list(data[:count])
    if bits == 16:
        return [data[2 * i] << 8 | data[2 * i + 1] for i in range(count)]
    out = []
    for i in range(count):
        bit = i * bits
        out.append((data[bit >> 3] >> (8 - bits - (bit & 7))) & ((1 << bits) - 1))
    return out


def unpack_rows(data, width, height, comps, bits):
    stride = (width * comps * bits + 7) // 8
    vals = []
    for y in range(height):
        vals += unpack(data[y * stride:(y + 1) * stride], width * comps, bits)
    return vals


def palette(data):
    i = data.find(b"pclr")
    if i < 0:
        return None
    ne, npc = struct.unpack(">HB", data[i + 4:i + 7])
    depths = [(b & 0x7F) + 1 for b in data[i + 7:i + 7 + npc]]
    p = i + 7 + npc
    table = []
    for _ in range(ne):
        row = []
        for d in depths:
            n = (d + 7) // 8
            row.append(int.from_bytes(data[p:p + n], "big"))
            p += n
        table.append(row)
    return table


def compare(expected, actual, comps):
    stats = []
    for c in range(comps):
        e = expected[c::comps]
        a = actual[c::comps]
        diffs = [abs(x - y) for x, y in zip(e, a)]
        stats.append((max(diffs) if diffs else 0, sum(d * d for d in diffs) / max(len(diffs), 1)))
    return stats


def main(directory):
    failed = False
    print("# Every JPXDecode image of the fetched real-world corpora (RealWorldJpxTests), regenerated by jpx-corpus-references.py:")
    print("# file | object | WxHxC@bits[+a<bits>[p]] | SHA-256 of samples then alpha | comparison with opj_decompress 2.5.4")
    print("# or: file | object | excluded | reason")
    lines = []
    for info_path in sorted(glob.glob(os.path.join(directory, "*.txt"))):
        stem = info_path[:-4]
        info = open(info_path).read().split("\n")
        file, number = info[0], int(info[1])
        if len(info) < 4 or not info[2]:
            reason = EXCLUSIONS.get((file, number))
            if reason is None:
                print(f"{file} {number}: not decoded and no exclusion reason", file=sys.stderr)
                failed = True
                reason = "not decoded"
            lines.append(f"{file} | {number} | excluded | {reason}")
            continue
        w, h, comps, bits = (int(v) for v in info[2].split())
        alpha_bits = None
        premultiplied = False
        colorspace = "none"
        for extra in info[3:]:
            if extra.startswith("alpha "):
                alpha_bits = int(extra.split()[1])
            if extra.startswith("colorspace "):
                colorspace = extra[len("colorspace "):]
            if extra == "premultiplied":
                premultiplied = True
        samples = open(stem + ".samples", "rb").read()
        digest = hashlib.sha256(samples)
        ours = unpack_rows(samples, w, h, comps, bits)
        alpha = None
        if alpha_bits is not None:
            alpha_data = open(stem + ".alpha", "rb").read()
            digest.update(alpha_data)
            alpha = unpack_rows(alpha_data, w, h, 1, alpha_bits)
        data = open(stem + ".jpx", "rb").read()
        ext = ".j2k" if data[:4] == b"\xff\x4f\xff\x51" else ".jp2"
        with tempfile.TemporaryDirectory() as tmp:
            src = os.path.join(tmp, "in" + ext)
            open(src, "wb").write(data)
            subprocess.run(["opj_decompress", "-i", src, "-o", os.path.join(tmp, "out.pgx")], capture_output=True)
            planes = [pgx(p) for p in sorted(glob.glob(os.path.join(tmp, "out*.pgx")), key=lambda p: int(p.rsplit("_", 1)[-1][:-4]) if "_" in os.path.basename(p) else 0)]
        if not planes:
            print(f"{file} {number}: OpenJPEG decodes nothing", file=sys.stderr)
            failed = True
            continue
        if "Indexed" in colorspace:
            table = palette(data)
            ours_mapped = []
            for v in ours:
                ours_mapped += table[min(v, len(table) - 1)]
            ours, comps_cmp = ours_mapped, len(table[0])
        else:
            comps_cmp = comps
        expected = []
        for i in range(w * h):
            for c in range(comps_cmp):
                pw, ph, depth, vals = planes[min(c, len(planes) - 1)]
                v = vals[i] if pw == w else vals[(i // w) * pw + i % w]
                target = bits if "Indexed" not in colorspace else depth
                if depth != target:
                    v = (v * ((1 << target) - 1) + ((1 << depth) - 1) // 2) // ((1 << depth) - 1)
                expected.append(v)
        stats = compare(expected, ours, comps_cmp)
        if alpha is not None:
            pw, ph, depth, vals = planes[comps_cmp] if len(planes) > comps_cmp else planes[-1]
            stats += compare(vals[:w * h], alpha, 1)
        exact = all(p == 0 for p, _ in stats)
        ok = all(p <= 4 and m <= 1 for p, m in stats)
        shape = f"{w}x{h}x{comps}@{bits}" + (f"+a{alpha_bits}{'p' if premultiplied else ''}" if alpha_bits else "")
        if exact:
            note = "exact"
        else:
            note = "PAE " + "/".join(str(p) for p, _ in stats) + " MSE " + "/".join(f"{m:.3f}" for _, m in stats)
        if not ok:
            print(f"{file} {number}: outside tolerance: {note}", file=sys.stderr)
            failed = True
        lines.append(f"{file} | {number} | {shape} | {digest.hexdigest()} | {note}")
    for line in sorted(lines):
        print(line)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
