#!/usr/bin/env python3
"""Generates the CFF data tables of the core from ``cff-data.txt`` in this directory.

Run with ``python3 -I src/Broadside/Fonts/Cff/Data/generate.py`` (stdlib only). The output is deterministic: re-running
it on unchanged input reproduces ``src/Broadside/Fonts/Cff/CffStandardData.g.cs`` byte for byte.

Input: ``cff-data.txt``, the tables of Adobe Technical Note #5176 (The Compact Font Format Specification, 4 Dec 03)
extracted from the specification with ``pdftotext -layout``: Appendix A (the 391 standard strings, SID 0-390, p.31-35),
Appendix B (StandardEncoding and ExpertEncoding as code -> SID, p.37-44) and Appendix C (the Expert and ExpertSubset
charsets as SIDs in GID order, p.45-50; ISOAdobe is SIDs 1-228 and needs no table). The extraction checked every
SID against its printed name, and the strings and both encodings were cross-checked against pdf.js (cff_parser.js
CFFStandardStrings, encodings.js) at commit c53f395e4057b501f478a7e98ed03d47c7c62a04.
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "CffStandardData.g.cs")


def read() -> dict[str, list[str]]:
    sections: dict[str, list[str]] = {}
    current = None
    with open(os.path.join(HERE, "cff-data.txt"), encoding="ascii") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if line.startswith("["):
                current = line[1:-1]
                sections[current] = []
                continue
            sections[current].append(line)
    return sections


def wrap(items: list[str], indent: str, width: int = 120) -> list[str]:
    lines, current = [], indent
    for item in items:
        piece = item + ","
        if len(current) + len(piece) + 1 > width and current.strip():
            lines.append(current.rstrip())
            current = indent
        current += piece + " "
    if current.strip():
        lines.append(current.rstrip())
    return lines


def main() -> int:
    sections = read()
    strings = []
    for sid, line in enumerate(sections["strings"]):
        number, name = line.split(" ", 1)
        assert int(number) == sid
        strings.append(name)
    assert len(strings) == 391
    encodings = {}
    for kind in ("Standard", "Expert"):
        rows = [tuple(map(int, line.split())) for line in sections["encoding " + kind]]
        assert [code for code, _ in rows] == list(range(256))
        encodings[kind] = [sid for _, sid in rows]
    charsets = {kind: list(map(int, sections["charset " + kind][0].split())) for kind in ("Expert", "ExpertSubset")}
    assert len(charsets["Expert"]) == 165 and len(charsets["ExpertSubset"]) == 86

    lines = [
        "// <auto-generated>",
        "// Generated by src/Broadside/Fonts/Cff/Data/generate.py from cff-data.txt (Adobe Technical Note #5176,",
        "// Appendices A, B and C). Do not edit; edit the generator or its input and re-run it.",
        "// </auto-generated>",
        "",
        "namespace Broadside.Fonts.Cff;",
        "",
        "/// <summary>The predefined data of the Compact Font Format: standard strings, encodings and charsets.</summary>",
        "/// <remarks>Adobe Technical Note #5176, Appendix A (p.31-35), Appendix B (p.37-44) and Appendix C (p.45-50).</remarks>",
        "internal static partial class CffStandardData",
        "{",
        "    /// <summary>The standard strings, by SID (0 <c>.notdef</c> to 390 <c>Semibold</c>); 5176 Appendix A.</summary>",
        "    internal static readonly string[] Strings =",
        "    [",
    ]
    lines += wrap(['"%s"' % s for s in strings], "        ")
    lines += ["    ];", ""]
    docs = {
        "StandardEncoding": "StandardEncoding as code to SID (0 = not encoded); 5176 Appendix B, p.37.",
        "ExpertEncoding": "ExpertEncoding as code to SID (0 = not encoded); 5176 Appendix B, p.40.",
        "ExpertCharset": "The Expert charset: SIDs of GIDs 1 to 165; 5176 Appendix C, p.47.",
        "ExpertSubsetCharset": "The ExpertSubset charset: SIDs of GIDs 1 to 86; 5176 Appendix C, p.49.",
    }
    tables = {
        "StandardEncoding": encodings["Standard"],
        "ExpertEncoding": encodings["Expert"],
        "ExpertCharset": charsets["Expert"],
        "ExpertSubsetCharset": charsets["ExpertSubset"],
    }
    for name, values in tables.items():
        # Arrays rather than ReadOnlySpan properties: RuntimeHelpers.CreateSpan allocates in unoptimized builds.
        lines += [f"    /// <summary>{docs[name]}</summary>", f"    internal static readonly ushort[] {name} =", "    ["]
        lines += wrap([str(v) for v in values], "        ")
        lines += ["    ];", ""]
    lines[-1:] = ["}"]
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
