<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Broadside.Fonts.Standard14/Broadside.Fonts.Standard14.csproj" />
    <ProjectReference Include="../Broadside.TestSupport/Broadside.TestSupport.csproj" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Verify.XunitV3" />
  </ItemGroup>

</Project>
