// <auto-generated>
// Generated by src/Broadside/Fonts/Data/generate.py. Do not edit; edit the generator or its inputs and re-run it.
//
// Derived from the Adobe Core 14 AFM files (Apache PDFBox commit 8712d47b075511a4c5a2829c3713ba2d538999bb,
// pdfbox/src/main/resources/org/apache/pdfbox/resources/afm/), which carry this notice (MustRead.html):
//
// This file and the 14 PostScript(R) AFM files it accompanies may be used, copied, and distributed for any
// purpose and without charge, with or without modification, provided that all copyright notices are retained;
// that the AFM files are not distributed without this file; that all modifications to this file or any of the
// AFM files are prominently noted in the modified file(s); and that this paragraph is not modified. Adobe
// Systems has no responsibility or obligation to support the use of the AFM files.
//
// MODIFIED: the AFM files were converted to C# tables; kerning, ligature and glyph bounding-box data were
// removed. The unmodified AFM files and MustRead.html are in src/Broadside/Fonts/Data/Afm/ and ship in the
// package under licenses/adobe-core14-afm/.
// </auto-generated>

namespace Broadside.Fonts;

/// <summary>Glyph names the built-in encodings and the Standard 14 metrics use, and the built-in encodings as name indexes.</summary>
/// <remarks>ISO 32000-2 Annex D (Tables D.2, D.4, D.5, D.6) and §9.6.5.4 Table 113; PostScript Language Reference Appendix E.7 (ISOLatin1Encoding).</remarks>
internal static partial class GlyphNameTable
{
    /// <summary>Every glyph name, in ordinal order.</summary>
    internal static readonly string[] Names =
    [
        "A", "AE", "AEsmall", "Aacute", "Aacutesmall", "Abreve", "Acircumflex", "Acircumflexsmall", "Acutesmall",
        "Adieresis", "Adieresissmall", "Agrave", "Agravesmall", "Alpha", "Amacron", "Aogonek", "Aring", "Aringsmall",
        "Asmall", "Atilde", "Atildesmall", "B", "Beta", "Brevesmall", "Bsmall", "C", "Cacute", "Caronsmall", "Ccaron",
        "Ccedilla", "Ccedillasmall", "Cedillasmall", "Chi", "Circumflexsmall", "Csmall", "D", "Dcaron", "Dcroat",
        "Delta", "Dieresissmall", "Dotaccentsmall", "Dsmall", "E", "Eacute", "Eacutesmall", "Ecaron", "Ecircumflex",
        "Ecircumflexsmall", "Edieresis", "Edieresissmall", "Edotaccent", "Egrave", "Egravesmall", "Emacron", "Eogonek",
        "Epsilon", "Esmall", "Eta", "Eth", "Ethsmall", "Euro", "F", "Fsmall", "G", "Gamma", "Gbreve", "Gcommaaccent",
        "Gravesmall", "Gsmall", "H", "Hsmall", "Hungarumlautsmall", "I", "Iacute", "Iacutesmall", "Icircumflex",
        "Icircumflexsmall", "Idieresis", "Idieresissmall", "Idotaccent", "Ifraktur", "Igrave", "Igravesmall",
        "Imacron", "Iogonek", "Iota", "Ismall", "J", "Jsmall", "K", "Kappa", "Kcommaaccent", "Ksmall", "L", "Lacute",
        "Lambda", "Lcaron", "Lcommaaccent", "Lslash", "Lslashsmall", "Lsmall", "M", "Macronsmall", "Msmall", "Mu", "N",
        "Nacute", "Ncaron", "Ncommaaccent", "Nsmall", "Ntilde", "Ntildesmall", "Nu", "O", "OE", "OEsmall", "Oacute",
        "Oacutesmall", "Ocircumflex", "Ocircumflexsmall", "Odieresis", "Odieresissmall", "Ogoneksmall", "Ograve",
        "Ogravesmall", "Ohungarumlaut", "Omacron", "Omega", "Omicron", "Oslash", "Oslashsmall", "Osmall", "Otilde",
        "Otildesmall", "P", "Phi", "Pi", "Psi", "Psmall", "Q", "Qsmall", "R", "Racute", "Rcaron", "Rcommaaccent",
        "Rfraktur", "Rho", "Ringsmall", "Rsmall", "S", "Sacute", "Scaron", "Scaronsmall", "Scedilla", "Scommaaccent",
        "Sigma", "Ssmall", "T", "Tau", "Tcaron", "Tcommaaccent", "Theta", "Thorn", "Thornsmall", "Tildesmall",
        "Tsmall", "U", "Uacute", "Uacutesmall", "Ucircumflex", "Ucircumflexsmall", "Udieresis", "Udieresissmall",
        "Ugrave", "Ugravesmall", "Uhungarumlaut", "Umacron", "Uogonek", "Upsilon", "Upsilon1", "Uring", "Usmall", "V",
        "Vsmall", "W", "Wsmall", "X", "Xi", "Xsmall", "Y", "Yacute", "Yacutesmall", "Ydieresis", "Ydieresissmall",
        "Ysmall", "Z", "Zacute", "Zcaron", "Zcaronsmall", "Zdotaccent", "Zeta", "Zsmall", "a", "a1", "a10", "a100",
        "a101", "a102", "a103", "a104", "a105", "a106", "a107", "a108", "a109", "a11", "a110", "a111", "a112", "a117",
        "a118", "a119", "a12", "a120", "a121", "a122", "a123", "a124", "a125", "a126", "a127", "a128", "a129", "a13",
        "a130", "a131", "a132", "a133", "a134", "a135", "a136", "a137", "a138", "a139", "a14", "a140", "a141", "a142",
        "a143", "a144", "a145", "a146", "a147", "a148", "a149", "a15", "a150", "a151", "a152", "a153", "a154", "a155",
        "a156", "a157", "a158", "a159", "a16", "a160", "a161", "a162", "a163", "a164", "a165", "a166", "a167", "a168",
        "a169", "a17", "a170", "a171", "a172", "a173", "a174", "a175", "a176", "a177", "a178", "a179", "a18", "a180",
        "a181", "a182", "a183", "a184", "a185", "a186", "a187", "a188", "a189", "a19", "a190", "a191", "a192", "a193",
        "a194", "a195", "a196", "a197", "a198", "a199", "a2", "a20", "a200", "a201", "a202", "a203", "a204", "a205",
        "a206", "a21", "a22", "a23", "a24", "a25", "a26", "a27", "a28", "a29", "a3", "a30", "a31", "a32", "a33", "a34",
        "a35", "a36", "a37", "a38", "a39", "a4", "a40", "a41", "a42", "a43", "a44", "a45", "a46", "a47", "a48", "a49",
        "a5", "a50", "a51", "a52", "a53", "a54", "a55", "a56", "a57", "a58", "a59", "a6", "a60", "a61", "a62", "a63",
        "a64", "a65", "a66", "a67", "a68", "a69", "a7", "a70", "a71", "a72", "a73", "a74", "a75", "a76", "a77", "a78",
        "a79", "a8", "a81", "a82", "a83", "a84", "a85", "a86", "a87", "a88", "a89", "a9", "a90", "a91", "a92", "a93",
        "a94", "a95", "a96", "a97", "a98", "a99", "aacute", "abreve", "acircumflex", "acute", "adieresis", "ae",
        "agrave", "aleph", "alpha", "amacron", "ampersand", "ampersandsmall", "angle", "angleleft", "angleright",
        "aogonek", "apple", "approxequal", "aring", "arrowboth", "arrowdblboth", "arrowdbldown", "arrowdblleft",
        "arrowdblright", "arrowdblup", "arrowdown", "arrowhorizex", "arrowleft", "arrowright", "arrowup",
        "arrowvertex", "asciicircum", "asciitilde", "asterisk", "asteriskmath", "asuperior", "at", "atilde", "b",
        "backslash", "bar", "beta", "braceex", "braceleft", "braceleftbt", "braceleftmid", "bracelefttp", "braceright",
        "bracerightbt", "bracerightmid", "bracerighttp", "bracketleft", "bracketleftbt", "bracketleftex",
        "bracketlefttp", "bracketright", "bracketrightbt", "bracketrightex", "bracketrighttp", "breve", "brokenbar",
        "bsuperior", "bullet", "c", "cacute", "caron", "carriagereturn", "ccaron", "ccedilla", "cedilla", "cent",
        "centinferior", "centoldstyle", "centsuperior", "chi", "circlemultiply", "circleplus", "circumflex", "club",
        "colon", "colonmonetary", "comma", "commaaccent", "commainferior", "commasuperior", "congruent", "copyright",
        "copyrightsans", "copyrightserif", "currency", "d", "dagger", "daggerdbl", "dcaron", "dcroat", "degree",
        "delta", "diamond", "dieresis", "divide", "dollar", "dollarinferior", "dollaroldstyle", "dollarsuperior",
        "dotaccent", "dotlessi", "dotmath", "dsuperior", "e", "eacute", "ecaron", "ecircumflex", "edieresis",
        "edotaccent", "egrave", "eight", "eightinferior", "eightoldstyle", "eightsuperior", "element", "ellipsis",
        "emacron", "emdash", "emptyset", "endash", "eogonek", "epsilon", "equal", "equivalence", "esuperior", "eta",
        "eth", "exclam", "exclamdown", "exclamdownsmall", "exclamsmall", "existential", "f", "ff", "ffi", "ffl", "fi",
        "figuredash", "five", "fiveeighths", "fiveinferior", "fiveoldstyle", "fivesuperior", "fl", "florin", "four",
        "fourinferior", "fouroldstyle", "foursuperior", "fraction", "g", "gamma", "gbreve", "gcommaaccent",
        "germandbls", "gradient", "grave", "greater", "greaterequal", "guillemotleft", "guillemotright",
        "guilsinglleft", "guilsinglright", "h", "heart", "hungarumlaut", "hyphen", "hypheninferior", "hyphensuperior",
        "i", "iacute", "icircumflex", "idieresis", "igrave", "imacron", "infinity", "integral", "integralbt",
        "integralex", "integraltp", "intersection", "iogonek", "iota", "isuperior", "j", "k", "kappa", "kcommaaccent",
        "l", "lacute", "lambda", "lcaron", "lcommaaccent", "less", "lessequal", "logicaland", "logicalnot",
        "logicalor", "lozenge", "lslash", "lsuperior", "m", "macron", "minus", "minute", "msuperior", "mu", "multiply",
        "n", "nacute", "ncaron", "ncommaaccent", "nine", "nineinferior", "nineoldstyle", "ninesuperior", "notelement",
        "notequal", "notsubset", "nsuperior", "ntilde", "nu", "numbersign", "o", "oacute", "ocircumflex", "odieresis",
        "oe", "ogonek", "ograve", "ohungarumlaut", "omacron", "omega", "omega1", "omicron", "one", "onedotenleader",
        "oneeighth", "onefitted", "onehalf", "oneinferior", "oneoldstyle", "onequarter", "onesuperior", "onethird",
        "ordfeminine", "ordmasculine", "oslash", "osuperior", "otilde", "p", "paragraph", "parenleft", "parenleftbt",
        "parenleftex", "parenleftinferior", "parenleftsuperior", "parenlefttp", "parenright", "parenrightbt",
        "parenrightex", "parenrightinferior", "parenrightsuperior", "parenrighttp", "partialdiff", "percent", "period",
        "periodcentered", "periodinferior", "periodsuperior", "perpendicular", "perthousand", "phi", "phi1", "pi",
        "plus", "plusminus", "product", "propersubset", "propersuperset", "proportional", "psi", "q", "question",
        "questiondown", "questiondownsmall", "questionsmall", "quotedbl", "quotedblbase", "quotedblleft",
        "quotedblright", "quoteleft", "quoteright", "quotesinglbase", "quotesingle", "r", "racute", "radical",
        "radicalex", "rcaron", "rcommaaccent", "reflexsubset", "reflexsuperset", "registered", "registersans",
        "registerserif", "rho", "ring", "rsuperior", "rupiah", "s", "sacute", "scaron", "scedilla", "scommaaccent",
        "second", "section", "semicolon", "seven", "seveneighths", "seveninferior", "sevenoldstyle", "sevensuperior",
        "sigma", "sigma1", "similar", "six", "sixinferior", "sixoldstyle", "sixsuperior", "slash", "space", "spade",
        "ssuperior", "sterling", "suchthat", "summation", "t", "tau", "tcaron", "tcommaaccent", "therefore", "theta",
        "theta1", "thorn", "three", "threeeighths", "threeinferior", "threeoldstyle", "threequarters",
        "threequartersemdash", "threesuperior", "tilde", "trademark", "trademarksans", "trademarkserif", "tsuperior",
        "two", "twodotenleader", "twoinferior", "twooldstyle", "twosuperior", "twothirds", "u", "uacute",
        "ucircumflex", "udieresis", "ugrave", "uhungarumlaut", "umacron", "underscore", "union", "universal",
        "uogonek", "upsilon", "uring", "v", "w", "weierstrass", "x", "xi", "y", "yacute", "ydieresis", "yen", "z",
        "zacute", "zcaron", "zdotaccent", "zero", "zeroinferior", "zerooldstyle", "zerosuperior", "zeta",
    ];

    /// <summary>StandardEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> StandardEncoding => StandardEncodingData;

    private static readonly short[] StandardEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 536, 696, 631, 504, 674, 414, 701, 661, 667, 437, 684, 485, 575, 675, 739, 798, 644, 766,
        754, 554, 547, 735, 727, 519, 621, 483, 726, 602, 531, 566, 692, 440, 0, 21, 25, 35, 42, 61, 63, 69, 72, 87,
        89, 93, 101, 105, 113, 134, 139, 141, 149, 157, 166, 182, 184, 186, 189, 195, 455, 443, 459, 435, 779, 700,
        202, 442, 467, 494, 512, 541, 559, 572, 578, 593, 594, 597, 610, 617, 632, 659, 691, 704, 719, 746, 772, 785,
        786, 788, 790, 794, 447, 444, 451, 436, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 537, 474, 743, 558, 793, 553, 725, 493, 703,
        698, 568, 570, 571, 545, 552, -1, 528, 495, 496, 676, -1, 660, 466, 702, 697, 699, 569, 524, 680, -1, 693, -1,
        565, 407, 481, 761, 611, 463, 508, 502, -1, 716, 473, -1, 574, 637, 469, 526, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 654, -1, -1, -1, -1, 98, 129, 114, 655, -1, -1, -1, -1, -1, 409, -1, -1,
        -1, 509, -1, -1, 608, 656, 636, 563, -1, -1, -1, -1,
    ];

    /// <summary>WinAnsiEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> WinAnsiEncoding => WinAnsiEncodingData;

    private static readonly short[] WinAnsiEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 536, 696, 631, 504, 674, 414, 703, 661, 667, 437, 684, 485, 575, 675, 739, 798, 644, 766,
        754, 554, 547, 735, 727, 519, 621, 483, 726, 602, 531, 566, 692, 440, 0, 21, 25, 35, 42, 61, 63, 69, 72, 87,
        89, 93, 101, 105, 113, 134, 139, 141, 149, 157, 166, 182, 184, 186, 189, 195, 455, 443, 459, 435, 779, 565,
        202, 442, 467, 494, 512, 541, 559, 572, 578, 593, 594, 597, 610, 617, 632, 659, 691, 704, 719, 746, 772, 785,
        786, 788, 790, 794, 447, 444, 451, 436, 466, 60, 466, 702, 553, 697, 524, 495, 496, 481, 680, 151, 570, 114,
        466, 197, 466, 466, 700, 701, 698, 699, 466, 528, 526, 761, 762, 721, 571, 636, 466, 796, 192, 740, 537, 474,
        743, 493, 793, 464, 725, 502, 490, 654, 568, 605, 575, 712, 611, 499, 685, 770, 760, 407, 615, 660, 676, 473,
        652, 655, 569, 651, 648, 758, 693, 11, 3, 6, 19, 9, 16, 1, 29, 51, 43, 46, 48, 81, 73, 75, 77, 58, 110, 123,
        116, 118, 132, 120, 616, 129, 173, 167, 169, 171, 190, 162, 563, 410, 404, 406, 441, 408, 422, 409, 472, 518,
        513, 515, 516, 582, 579, 580, 581, 535, 629, 638, 633, 634, 658, 635, 503, 656, 776, 773, 774, 775, 791, 753,
        792,
    ];

    /// <summary>MacRomanEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> MacRomanEncoding => MacRomanEncodingData;

    private static readonly short[] MacRomanEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 536, 696, 631, 504, 674, 414, 703, 661, 667, 437, 684, 485, 575, 675, 739, 798, 644, 766,
        754, 554, 547, 735, 727, 519, 621, 483, 726, 602, 531, 566, 692, 440, 0, 21, 25, 35, 42, 61, 63, 69, 72, 87,
        89, 93, 101, 105, 113, 134, 139, 141, 149, 157, 166, 182, 184, 186, 189, 195, 455, 443, 459, 435, 779, 565,
        202, 442, 467, 494, 512, 541, 559, 572, 578, 593, 594, 597, 610, 617, 632, 659, 691, 704, 719, 746, 772, 785,
        786, 788, 790, 794, 447, 444, 451, 436, -1, 9, 16, 29, 43, 110, 120, 171, 404, 410, 406, 408, 441, 422, 472,
        513, 518, 515, 516, 579, 582, 580, 581, 629, 633, 638, 634, 635, 658, 773, 776, 774, 775, 495, 499, 474, 743,
        725, 466, 660, 563, 712, 490, 762, 407, 502, -1, 1, 129, -1, 685, -1, -1, 793, 615, -1, -1, -1, -1, -1, 654,
        655, -1, 409, 656, 693, 537, 605, -1, 553, -1, -1, 568, 569, 524, 740, 11, 19, 132, 114, 636, 528, 526, 698,
        699, 700, 701, 503, -1, 792, 192, 558, 493, 570, 571, 545, 552, 496, 676, 702, 697, 680, 6, 46, 3, 48, 51, 73,
        75, 77, 81, 116, 118, -1, 123, 167, 169, 173, 509, 481, 761, 611, 463, 508, 716, 473, 574, 637, 469,
    ];

    /// <summary>MacExpertEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> MacExpertEncoding => MacExpertEncodingData;

    private static readonly short[] MacExpertEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 539, 71, 476, 506, 507, 415, 8, 665, 671, 767, 645, 485, 575, 675, 558, 800, 650, 769,
        757, 556, 550, 737, 730, 521, 623, 483, 726, -1, 759, -1, 695, -1, -1, -1, -1, 59, -1, -1, 651, 648, 758, 646,
        755, 548, 728, 653, 771, -1, -1, -1, -1, -1, -1, 542, 545, 552, 543, 544, 664, -1, 670, 33, 576, 67, 18, 24,
        34, 41, 56, 62, 68, 70, 86, 88, 92, 100, 103, 109, 131, 138, 140, 148, 156, 165, 181, 183, 185, 188, 194, 201,
        484, 647, 718, 164, -1, -1, 439, 477, -1, -1, -1, -1, 4, 12, 7, 10, 20, 17, 30, 44, 52, 47, 49, 74, 82, 76, 78,
        111, 117, 124, 119, 121, 133, 168, 174, 170, 172, -1, 522, 555, 756, 736, 520, 729, 152, -1, 475, 768, -1, 39,
        -1, 27, 657, 549, -1, 487, 677, 191, -1, 505, -1, -1, 163, -1, 622, 799, 198, 2, 130, 694, 649, 99, -1, -1, -1,
        -1, -1, -1, 31, -1, -1, -1, -1, -1, 115, 546, 577, -1, -1, -1, -1, 538, -1, 193, -1, 652, 770, 760, 557, 551,
        738, 731, 624, 801, -1, 533, 717, 765, -1, -1, 592, 742, 511, -1, -1, -1, -1, -1, 609, 122, 23, 102, 465, 628,
        614, 488, 678, 40, 147, -1, -1, -1, -1,
    ];

    /// <summary>SymbolEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> SymbolEncoding => SymbolEncodingData;

    private static readonly short[] SymbolEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 536, 781, 631, 540, 674, 414, 744, 661, 667, 438, 684, 485, 612, 675, 739, 798, 644, 766,
        754, 554, 547, 735, 727, 519, 621, 483, 726, 602, 531, 566, 692, 489, 13, 22, 32, 38, 55, 135, 64, 57, 85, 752,
        90, 95, 104, 112, 128, 136, 161, 146, 155, 158, 178, 733, 127, 187, 137, 200, 455, 750, 459, 679, 779, 707,
        412, 445, 478, 500, 530, 681, 560, 534, 591, 682, 595, 599, 615, 630, 643, 683, 751, 715, 732, 747, 783, 642,
        641, 789, 690, 802, 447, 444, 451, 734, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 60, 179, 613, 603, 558, 584, 553, 482, 501, 573,
        741, 423, 431, 433, 432, 429, 499, 685, 724, 567, 616, 689, 673, 466, 503, 626, 532, 421, 524, 434, 430, 470,
        411, 80, 145, 787, 479, 480, 527, 589, 780, 688, 711, 627, 687, 710, 523, 625, 416, 564, 714, 492, 764, 686,
        706, 510, 605, 604, 606, 424, 426, 428, 427, 425, 607, 417, 713, 491, 763, 745, 666, 663, 662, 458, 457, 456,
        450, 449, 448, 446, -1, 418, 585, 588, 587, 586, 672, 669, 668, 462, 461, 460, 454, 453, 452, -1,
    ];

    /// <summary>ZapfDingbatsEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> ZapfDingbatsEncoding => ZapfDingbatsEncodingData;

    private static readonly short[] ZapfDingbatsEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 203, 310, 314, 328, 339, 350, 221, 220, 219, 215, 222, 233, 244, 255, 266, 210, 277, 288,
        299, 311, 319, 320, 321, 322, 323, 324, 325, 326, 361, 372, 383, 393, 204, 327, 329, 330, 331, 332, 333, 334,
        335, 336, 337, 338, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 351, 352, 353, 354, 355, 356, 357, 358,
        359, 360, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 373, 374, 375, 376, 377, 315, 378, 316, 379, 380,
        381, 382, 384, 385, 386, 387, 401, 402, 403, 205, -1, 392, 394, 397, 398, 395, 396, 317, 388, 318, 389, 390,
        391, 399, 400, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 206, 207, 208, 209,
        211, 212, 213, 218, 217, 216, 214, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 234, 235, 236, 237, 238,
        239, 240, 241, 242, 243, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 256, 257, 258, 259, 260, 261, 262,
        263, 264, 265, 267, 268, 270, 271, 306, 272, 302, 273, 274, 275, 276, 278, 279, 280, 281, 269, 282, 283, 284,
        285, 286, 287, 303, 289, 309, 290, 312, 291, -1, 313, 292, 293, 307, 294, 304, 308, 295, 305, 296, 297, 298,
        300, 301, -1,
    ];

    /// <summary>MacOSRomanEncoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> MacOSRomanEncoding => MacOSRomanEncodingData;

    private static readonly short[] MacOSRomanEncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 536, 696, 631, 504, 674, 414, 703, 661, 667, 437, 684, 485, 575, 675, 739, 798, 644, 766,
        754, 554, 547, 735, 727, 519, 621, 483, 726, 602, 531, 566, 692, 440, 0, 21, 25, 35, 42, 61, 63, 69, 72, 87,
        89, 93, 101, 105, 113, 134, 139, 141, 149, 157, 166, 182, 184, 186, 189, 195, 455, 443, 459, 435, 779, 565,
        202, 442, 467, 494, 512, 541, 559, 572, 578, 593, 594, 597, 610, 617, 632, 659, 691, 704, 719, 746, 772, 785,
        786, 788, 790, 794, 447, 444, 451, 436, -1, 9, 16, 29, 43, 110, 120, 171, 404, 410, 406, 408, 441, 422, 472,
        513, 518, 515, 516, 579, 582, 580, 581, 629, 633, 638, 634, 635, 658, 773, 776, 774, 775, 495, 499, 474, 743,
        725, 466, 660, 563, 712, 490, 762, 407, 502, 626, 1, 129, 584, 685, 603, 567, 793, 615, 673, 745, 686, 683,
        585, 654, 655, 127, 409, 656, 693, 537, 605, 706, 553, 421, 38, 568, 569, 524, 740, 11, 19, 132, 114, 636, 528,
        526, 698, 699, 700, 701, 503, 607, 792, 192, 558, 60, 570, 571, 545, 552, 496, 676, 702, 697, 680, 6, 46, 3,
        48, 51, 73, 75, 77, 81, 116, 118, 420, 123, 167, 169, 173, 509, 481, 761, 611, 463, 508, 716, 473, 574, 637,
        469,
    ];

    /// <summary>ISOLatin1Encoding: for each code, the index of its glyph name in <see cref="Names"/>, or -1.</summary>
    internal static ReadOnlySpan<short> ISOLatin1Encoding => ISOLatin1EncodingData;

    private static readonly short[] ISOLatin1EncodingData =
    [
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, 740, 536, 696, 631, 504, 674, 414, 701, 661, 667, 437, 684, 485, 612, 675, 739, 798, 644, 766,
        754, 554, 547, 735, 727, 519, 621, 483, 726, 602, 531, 566, 692, 440, 0, 21, 25, 35, 42, 61, 63, 69, 72, 87,
        89, 93, 101, 105, 113, 134, 139, 141, 149, 157, 166, 182, 184, 186, 189, 195, 455, 443, 459, 435, 779, 700,
        202, 442, 467, 494, 512, 541, 559, 572, 578, 593, 594, 597, 610, 617, 632, 659, 691, 704, 719, 746, 772, 785,
        786, 788, 790, 794, 447, 444, 451, 436, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        509, 565, 407, 481, 761, 611, 463, 508, 502, -1, 716, 473, -1, 574, 637, 469, 740, 537, 474, 743, 493, 793,
        464, 725, 502, 490, 654, 568, 605, 575, 712, 611, 499, 685, 770, 760, 407, 615, 660, 676, 473, 652, 655, 569,
        651, 648, 758, 693, 11, 3, 6, 19, 9, 16, 1, 29, 51, 43, 46, 48, 81, 73, 75, 77, 58, 110, 123, 116, 118, 132,
        120, 616, 129, 173, 167, 169, 171, 190, 162, 563, 410, 404, 406, 441, 408, 422, 409, 472, 518, 513, 515, 516,
        582, 579, 580, 581, 535, 629, 638, 633, 634, 658, 635, 503, 656, 776, 773, 774, 775, 791, 753, 792,
    ];
}
