// <auto-generated>
// Generated by src/Broadside.Fonts.Cmaps/Data/generate.py from Adobe cmap-resources
// (https://github.com/adobe-type-tools/cmap-resources, f5cf3bca7fdfeaceb77aa82847e974f2306c20b4, BSD-3-Clause; see
// THIRD-PARTY-NOTICES.txt). Do not edit.
// </auto-generated>
namespace Broadside.Fonts;

/// <summary>The predefined CMaps of ISO 32000-2 Table 116 (Identity aside): character collection, writing mode, codespace.</summary>
internal static partial class PredefinedCMapTable
{
    private static readonly Entry[] Entries =
    [
        new("GB-EUC-H", "Adobe", "GB1", 0, 0, [new(1, 0x00, 0x80), new(2, 0xA1A1, 0xFEFE)]),
        new("GB-EUC-V", "Adobe", "GB1", 0, 1, [new(1, 0x00, 0x80), new(2, 0xA1A1, 0xFEFE)]),
        new("GBpc-EUC-H", "Adobe", "GB1", 0, 0, [new(1, 0x00, 0x80), new(2, 0xA1A1, 0xFCFE), new(1, 0xFD, 0xFF)]),
        new("GBpc-EUC-V", "Adobe", "GB1", 0, 1, [new(1, 0x00, 0x80), new(2, 0xA1A1, 0xFCFE), new(1, 0xFD, 0xFF)]),
        new("GBK-EUC-H", "Adobe", "GB1", 2, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0xFEFE)]),
        new("GBK-EUC-V", "Adobe", "GB1", 2, 1, [new(1, 0x00, 0x80), new(2, 0x8140, 0xFEFE)]),
        new("GBKp-EUC-H", "Adobe", "GB1", 2, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0xFEFE)]),
        new("GBKp-EUC-V", "Adobe", "GB1", 2, 1, [new(1, 0x00, 0x80), new(2, 0x8140, 0xFEFE)]),
        new("GBK2K-H", "Adobe", "GB1", 6, 0, [new(1, 0x00, 0x7F), new(4, 0x81308130, 0xFE39FE39), new(2, 0x8140, 0xFEFE)]),
        new("GBK2K-V", "Adobe", "GB1", 6, 1, [new(1, 0x00, 0x7F), new(4, 0x81308130, 0xFE39FE39), new(2, 0x8140, 0xFEFE)]),
        new("UniGB-UCS2-H", "Adobe", "GB1", 4, 0, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniGB-UCS2-V", "Adobe", "GB1", 4, 1, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniGB-UTF16-H", "Adobe", "GB1", 6, 0, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("UniGB-UTF16-V", "Adobe", "GB1", 6, 1, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("B5pc-H", "Adobe", "CNS1", 0, 0, [new(1, 0x00, 0x80), new(2, 0xA140, 0xFCFE), new(1, 0xFD, 0xFF)]),
        new("B5pc-V", "Adobe", "CNS1", 0, 1, [new(1, 0x00, 0x80), new(2, 0xA140, 0xFCFE), new(1, 0xFD, 0xFF)]),
        new("HKscs-B5-H", "Adobe", "CNS1", 6, 0, [new(1, 0x00, 0x80), new(2, 0x8740, 0xFEFE)]),
        new("HKscs-B5-V", "Adobe", "CNS1", 6, 1, [new(1, 0x00, 0x80), new(2, 0x8740, 0xFEFE)]),
        new("ETen-B5-H", "Adobe", "CNS1", 0, 0, [new(1, 0x00, 0x80), new(2, 0xA140, 0xFEFE)]),
        new("ETen-B5-V", "Adobe", "CNS1", 0, 1, [new(1, 0x00, 0x80), new(2, 0xA140, 0xFEFE)]),
        new("ETenms-B5-H", "Adobe", "CNS1", 0, 0, [new(1, 0x00, 0x80), new(2, 0xA140, 0xFEFE)]),
        new("ETenms-B5-V", "Adobe", "CNS1", 0, 1, [new(1, 0x00, 0x80), new(2, 0xA140, 0xFEFE)]),
        new("CNS-EUC-H", "Adobe", "CNS1", 0, 0, [new(1, 0x00, 0x80), new(4, 0x8EA1A1A1, 0x8EA1FEFE), new(4, 0x8EA2A1A1, 0x8EA2FEFE), new(4, 0x8EA3A1A1, 0x8EA3FEFE), new(2, 0xA1A1, 0xFEFE)]),
        new("CNS-EUC-V", "Adobe", "CNS1", 0, 1, [new(1, 0x00, 0x80), new(4, 0x8EA1A1A1, 0x8EA1FEFE), new(4, 0x8EA2A1A1, 0x8EA2FEFE), new(4, 0x8EA3A1A1, 0x8EA3FEFE), new(2, 0xA1A1, 0xFEFE)]),
        new("UniCNS-UCS2-H", "Adobe", "CNS1", 3, 0, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniCNS-UCS2-V", "Adobe", "CNS1", 3, 1, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniCNS-UTF16-H", "Adobe", "CNS1", 7, 0, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("UniCNS-UTF16-V", "Adobe", "CNS1", 7, 1, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("83pv-RKSJ-H", "Adobe", "Japan1", 1, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC), new(1, 0xFD, 0xFF)]),
        new("90ms-RKSJ-H", "Adobe", "Japan1", 2, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("90ms-RKSJ-V", "Adobe", "Japan1", 2, 1, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("90msp-RKSJ-H", "Adobe", "Japan1", 2, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("90msp-RKSJ-V", "Adobe", "Japan1", 2, 1, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("90pv-RKSJ-H", "Adobe", "Japan1", 1, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC), new(1, 0xFD, 0xFF)]),
        new("Add-RKSJ-H", "Adobe", "Japan1", 1, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("Add-RKSJ-V", "Adobe", "Japan1", 1, 1, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("EUC-H", "Adobe", "Japan1", 1, 0, [new(1, 0x00, 0x80), new(2, 0x8EA0, 0x8EDF), new(2, 0xA1A1, 0xFEFE)]),
        new("EUC-V", "Adobe", "Japan1", 1, 1, [new(1, 0x00, 0x80), new(2, 0x8EA0, 0x8EDF), new(2, 0xA1A1, 0xFEFE)]),
        new("Ext-RKSJ-H", "Adobe", "Japan1", 2, 0, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("Ext-RKSJ-V", "Adobe", "Japan1", 2, 1, [new(1, 0x00, 0x80), new(2, 0x8140, 0x9FFC), new(1, 0xA0, 0xDF), new(2, 0xE040, 0xFCFC)]),
        new("H", "Adobe", "Japan1", 1, 0, [new(2, 0x2121, 0x7E7E)]),
        new("V", "Adobe", "Japan1", 1, 1, [new(2, 0x2121, 0x7E7E)]),
        new("UniJIS-UCS2-H", "Adobe", "Japan1", 4, 0, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniJIS-UCS2-V", "Adobe", "Japan1", 4, 1, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniJIS-UCS2-HW-H", "Adobe", "Japan1", 4, 0, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniJIS-UCS2-HW-V", "Adobe", "Japan1", 4, 1, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniJIS-UTF16-H", "Adobe", "Japan1", 7, 0, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("UniJIS-UTF16-V", "Adobe", "Japan1", 7, 1, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("KSC-EUC-H", "Adobe", "Korea1", 0, 0, [new(1, 0x00, 0x80), new(2, 0xA1A1, 0xFEFE)]),
        new("KSC-EUC-V", "Adobe", "Korea1", 0, 1, [new(1, 0x00, 0x80), new(2, 0xA1A1, 0xFEFE)]),
        new("KSCms-UHC-H", "Adobe", "Korea1", 1, 0, [new(1, 0x00, 0x80), new(2, 0x8141, 0xFEFE)]),
        new("KSCms-UHC-V", "Adobe", "Korea1", 1, 1, [new(1, 0x00, 0x80), new(2, 0x8141, 0xFEFE)]),
        new("KSCms-UHC-HW-H", "Adobe", "Korea1", 1, 0, [new(1, 0x00, 0x80), new(2, 0x8141, 0xFEFE)]),
        new("KSCms-UHC-HW-V", "Adobe", "Korea1", 1, 1, [new(1, 0x00, 0x80), new(2, 0x8141, 0xFEFE)]),
        new("KSCpc-EUC-H", "Adobe", "Korea1", 0, 0, [new(1, 0x00, 0x84), new(2, 0xA141, 0xFDFE), new(1, 0xFE, 0xFF)]),
        new("UniKS-UCS2-H", "Adobe", "Korea1", 1, 0, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniKS-UCS2-V", "Adobe", "Korea1", 1, 1, [new(2, 0x0000, 0xD7FF), new(2, 0xE000, 0xFFFF)]),
        new("UniKS-UTF16-H", "Adobe", "Korea1", 1, 0, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
        new("UniKS-UTF16-V", "Adobe", "Korea1", 1, 1, [new(2, 0x0000, 0xD7FF), new(4, 0xD800DC00, 0xDBFFDFFF), new(2, 0xE000, 0xFFFF)]),
    ];
}
