using Broadside.TestSupport;

namespace Broadside.Tests.Files;

/// <summary>PDF Declarations in document-level and object-level XMP. PDF Declarations §7 and §8.</summary>
public sealed class DeclarationTests
{
    [Fact]
    public void Document_declarations_come_from_the_catalog_XMP_with_trimmed_URIs_and_claims()
    {
        using PdfDocument document = PdfDocument.Open(Corpus.Path("declarations.pdf"));

        IReadOnlyList<PdfDeclaration> declarations = document.Declarations;

        Assert.Equal(["https://pdfa.org/declarations#iso32005", "http://pdfa.org/declarations/wtpdf/#reuse1.0"], declarations.Select(declaration => declaration.ConformsTo));
        PdfDeclarationClaim claim = Assert.Single(declarations[0].Claims);
        Assert.Equal("Broadside corpus", claim.ClaimedBy);
        Assert.Equal("2024-05-06", claim.DateText);
        Assert.Equal(new DateTimeOffset(2024, 5, 6, 0, 0, 0, TimeSpan.Zero), claim.Date!.Value.Value);
        Assert.Equal("Generated by generate.py", claim.Credentials);
        Assert.Equal("#ef=report.html", claim.Report);
        Assert.Empty(declarations[1].Claims);
        Assert.Empty(document.Diagnostics);
    }

    [Fact]
    public void An_object_level_declaration_is_read_from_the_objects_metadata()
    {
        using PdfDocument document = PdfDocument.Open(Corpus.Path("declarations.pdf"));

        PdfObjectMetadata page = document.EnumerateObjectMetadata().Single(metadata => metadata.Location == PdfMetadataLocation.Page);

        Assert.Equal("http://pdfa.org/declarations/wtpdf/#accessibility1.0", Assert.Single(page.Declarations).ConformsTo);
    }

    [Fact]
    public void A_document_without_declarations_has_none()
    {
        using PdfDocument withMetadata = PdfDocument.Open(Corpus.Path("metadata-xmp.pdf"));
        using PdfDocument withoutMetadata = PdfDocument.Open(Corpus.Path("empty-page.pdf"));

        Assert.Empty(withMetadata.Declarations);
        Assert.Empty(withoutMetadata.Declarations);
    }
}
